version: '3.3'

networks:
  web:
    external: true

services:
  router:
    container_name: router
    image: traefik:v2.4
    command: --certificatesresolvers.lets-encrypt.acme.email=$ACME_EMAIL \
             --certificatesresolvers.myresolver.acme.dnschallenge.provider=$DNS_PROVIDER
    network_mode: host
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml:ro
      - ./traefik_dynamic.toml:/traefik_dynamic.toml:ro
      - ./acme.json:/acme.json
      - ./users:/app/users:ro
    env_file:
      - .env
    restart: unless-stopped

