version: '3.5'

services:
  router:
    container_name: router
    image: traefik:v1.6
    command: --docker --docker.watch --docker.exposedbydefault=false --web \
            --defaultEntryPoints="http,https" \
            --entryPoints="Name:https Address::443 TLS" \
            --entryPoints="Name:http Address::80" \
            --acme=true --acme.caserver=https://acme-v02.api.letsencrypt.org/directory \
            --acme.email=$ACME_EMAIL --acme.onhostrule=true --acme.acmelogging=true \
            --acme.entrypoint=https --acme.dnschallenge=true --acme.dnschallenge.provider=$DNS_PROVIDER \
            --acme.storage="/etc/traefik/conf/acme.json" \
            --logLevel=DEBUG
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
      - "./acme.json:/etc/traefik/conf/acme.json:rw"
    networks:
      - router
    env_file:
      - .env
    restart: always

networks:
  router:
    name: router
    driver: bridge
