[http.middlewares]
  [http.middlewares.simpleAuth.basicAuth]
    usersFile = "/app/users"

  [http.middlewares.secHeaders.headers]
    browserXssFilter = true
    contentTypeNosniff = true
    frameDeny = true
    sslRedirect = true
    forceSTSHeader = true
    stsIncludeSubdomains = true
    stsPreload = true
    stsSeconds = 31536000
    sslForceHost = true

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    sniStrict = true
    preferServerCipherSuites = true
    cipherSuites = [
      "TLS_AES_128_GCM_SHA256",
      "TLS_CHACHA20_POLY1305_SHA256",
      "TLS_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
    ]
    curvePreferences = ["CurveP521", "CurveP384"]

#[http.routers]
#  [http.routers.api]
#    rule = "Host(`monitor.example.com`)"
#    entrypoints = ["websecure"]
#    middlewares = ["simpleAuth"]
#    service = "api@internal"
#    [http.routers.api.tls]
#      certResolver = "lets-encrypt"

